### ISSUE TITLE
State of Detox

### ISSUE THREAD

**Issue by SnowyCoder** [Detox/chat#1]
Hello, I was searching for a distributed signaling system for a long time,
There doesn't seem to be any popular solutions yet, but your library seems close to it.
How is the sate of Detox? Is the DHT working?

**Comment by nazar-pc** [comment]
It is not under active development because I didn't have time to work on it in recent years.

The basics, includng DHT, are working, but it needs rewrite to TypeScript from LiveScript to make contributions easier and on architecture level is is not fully delivering to design goals due to permissionless networking challenges being hard (if not impossible) to resolve. Public bootstrap nodes were taken down, but the code is available, anyone can run them.

I might get back to this once https://subspace.network/ is live, strong and independent. I still believe there is a value and need for such a project.

**Comment by SnowyCoder** [comment]
Thanks for the quick response.
I'm thinking about working on a similar thing (but just on the DHT part) on my thesis so this is really interesting.

I've also seen that you're Ukrainian, I really hope you're safe.
